name: AziSwitch
version: @version@
main: com.github.mori01231.aziswitch.AziSwitch
author: Mori01231
description: Switch between Admin mode and Member mode


commands:
  switch:
    description: Change between admin mode and user mode.
    usage: Syntax Error! Simply type /switch to change gamemodes.

permissions:
  aziswitch.*:
    description: Gives access to all Aziswitch commands